### ISSUE TITLE
weekends and holidays problems

### ISSUE THREAD

**Issue by rasharp1216** [AnKing-Memberships/ankiweb-placeholder#11]
#### Problem description

add-on will not save preferences or execute the function to reschedule cards, currently using the most up-to-date anki Qt6.
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 2.1.5 qt6

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54 qt6
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Use Qt5. None of our addons really support Qt6 yet
