### ISSUE TITLE
 Export Anki to PDF not working

### ISSUE THREAD

**Issue by tajmcp** [AnKing-Memberships/ankiweb-placeholder#13]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - X I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - X I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using? Version ⁨2.1.49

```
2.1.##
```

#### Your question

I am receiving this error message after downloading 
Export Anki to PDF. I have deleted the add on and re downloded it but I keep getting the same message.

An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading '⁨PDF Exporter⁩':
⁨Traceback (most recent call last):
  File "aqt/addons.py", line 230, in loadAddons
  File "/Users/tajeramcpherson/Library/Application Support/Anki2/addons21/1442112168/__init__.py", line 7, in <module>
    from .clayout import add_export_template_managment_to_clayout
  File "/Users/tajeramcpherson/Library/Application Support/Anki2/addons21/1442112168/clayout.py", line 182, in <module>
    prompt: str, choices: list[str], startrow: int = 0, parent: Any = None
TypeError: 'type' object is not subscriptable

**Comment by AnKingMed** [comment]
I was able to replicate this. Are you open to upgrading to 2.1.54 Qt5? It is working on that version at the moment.

**Comment by tajmcp** [comment]
Thanks so much it worked!
