### ISSUE TITLE
AttributeError: 'QDateTime' object has no attribute 'setTime_t'

### ISSUE THREAD

**Issue by guillem-palau-salva** [AnKing-Memberships/ankiweb-placeholder#14]
## Which add-on is this about?

Exam notifier

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

https://app.kajabi.com/admin/comments/2156140012

select deck options and scroll down to the "add-ons" section (above the "Advanced" section for me). The section says:

"If you're using an add-on that hasn't been updated to use this new screen yet, you can access the old deck options screen by holding down the shift key when opening the options.

Looking for Exam Notifier's options? Click here!"

Clicking on that link pops the error up. I have also tried the shift+options, and this add-on will not appear in the old version of the options menu either.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.154 Qt5
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
rror
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-26 18:01:42
Add-ons possibly involved: ⁨Exam Notifier⁩

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 42, in cmd
File "aqt.webview", line 149, in _onCmd
File "aqt.webview", line 618, in _onBridgeCmd
File "aqt.hooks_gen", line 4358, in __call__
File "/Users/drewcosta/Library/Application Support/Anki2/addons21/exam_notifier/deck_options.py", line 150, in on_webview_did_receive_js_message
DeckConf(self._main_window, deck_legacy)
File "aqt.deckconf", line 40, in __init__
File "aqt.hooks_gen", line 1604, in __call__
File "/Users/drewcosta/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 109, in on_deck_config_gui_loaded
deck_config_tab = self._factory(parent=deck_conf_dialog)
File "/Users/drewcosta/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 63, in __init__
self._qdatetime_from_epoch(unix_time_now)
File "/Users/drewcosta/Library/Application Support/Anki2/addons21/exam_notifier/deck_options_legacy.py", line 89, in _qdatetime_from_epoch
qdatetime.setTime_t(unix_epoch)
AttributeError: 'QDateTime' object has no attribute 'setTime_t'
```

**Comment by AnKingMed** [comment]
It looks like they're on Qt6. We are only supporting Qt5, but we're working on Qt6 updates at the moment and plan to release the add-on publicly after things are updated. @BlueGreenMagick has been working on it.

**Comment by guillem-palau-salva** [comment]
Oh yeah I've overlooked this one. My apologies. Qt6 is the first thing I ask.

**Comment by BlueGreenMagick** [comment]
I think this issue is already fixed and you just need to update the addon
https://github.com/AnKingMed/exam-notifier/releases
