### ISSUE TITLE
Exam notifier dead link

### ISSUE THREAD

**Issue by guillem-palau-salva** [AnKing-Memberships/ankiweb-placeholder#15]
## Which add-on is this about?

Exam notifier 

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Tools->add-ons->view add-on page opens https://github.com/glutanimate/exam-notifier which returns 404. Perhaps we could link the placeholder instead https://ankiweb.net/shared/info/599952588

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@BlueGreenMagick can we make this change?

**Comment by BlueGreenMagick** [comment]
Moved to exam-notifier repo
