### ISSUE TITLE
"UWorld QID to Anki Search" Add-On Bit.Ly Not Working

### ISSUE THREAD

**Issue by Cain-Mosni** [AnKing-Memberships/ankiweb-placeholder#20]
## Which add-on is this about?
UWorld QID to Anki Search

#### Problem description

I'm trying to download this add-on after becoming a member and it is not working for me. Is this happening to others as well?

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you describe what's happening? What is happening when you click the Bitly link? You can provide screenshots if possible

**Comment by Cain-Mosni** [comment]
Hi, the Bitly was just not loading a download link, but it works now! Thank you!
