### ISSUE TITLE
holiday/weekend rescheduling 

### ISSUE THREAD

**Issue by hkpham9** [AnKing-Memberships/ankiweb-placeholder#21]
Weekends & Holidays add on 

#### Problem description

I rescheduled my cards for 12/17-12/22 ; the amount of cards i had for review every day was about ~200. when the date range ended, but card count was up to 700+. After i finished those cards, all of my reviews were gone. my heat map doesnt  show any future reviews either... i disabled the add on but i dont know what happened. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you please send screenshots?

Also please send your collection. Go to file-> export then export the .colpkg.  Don't include media

**Comment by hkpham9** [comment]
Attachment available until Jan 26, 2023
Click to Download
 ***@***.***
20.5 MB

**Comment by hkpham9** [comment]
<img width="896" alt="Screenshot 2022-12-27 at 9 38 44 AM" src="https://user-images.githubusercontent.com/121474150/209702207-c8a2dad9-e0e3-43d9-93ec-7f65109c3947.png">

**Comment by AnKingMed** [comment]
It seems I can't download the file. Can you upload it directly on github?

**Comment by hkpham9** [comment]
I tried to upload it but it wouldn’t let me. Is there another way for me to upload it on there?

**Comment by AnKingMed** [comment]
You probably need to zip it.  Or just email me

**Comment by hkpham9** [comment]
[Uploading collection-2022-12-27@14-58-13.colpkg.zip…]()

**Comment by hkpham9** [comment]
Attachment available until Jan 26, 2023
Click to Download
 ***@***.***
20.5 MB

**Comment by AnKingMed** [comment]
That's not working either. Are you responding to your comments directly on your email? You probably need to actually get on github.com

**Comment by hkpham9** [comment]
I did both, I uploaded it on there after I emailed you a copy. Did that one not work either?

**Comment by AnKingMed** [comment]
Nope. Just email me at ankingmed@gmail.com
