### ISSUE TITLE
Question about unlocking new cards using the Weekends and Holidays Add-on

### ISSUE THREAD

**Issue by gerarlunap** [AnKing-Memberships/ankiweb-placeholder#22]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54 (b6a7760c)⁩
```

#### Your question

*When I unlock new cards to study, does the add-on automatically reschedules those new cards or do I need to do something for them to not show up on the days I previously configured to be spared?*

**Comment by AnKingMed** [comment]
It shouldn't affect new cards at all
