### ISSUE TITLE
Calculate new cards to do addon 

### ISSUE THREAD

**Issue by dalton264** [AnKing-Memberships/ankiweb-placeholder#23]
## Which add-on is this about?
Calculate new cards to do addon 

#### Problem description

Hi I cant get the calculate new cards addon to work. The example option works but I cannot figure out how to get it to count my decks. Any deck I chose it just tells me that I have 0 cards to do. 
For example if my deck is Gross anatomy both semester
I have tried Tag: Gross anatomy both semester
I have also tried deck: Gross anatomy both semester

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.56 q5
though i tried several version ranging back to 2.1.44 
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
When you put that exact search into the browser, how many cards show up? Are those cards suspended?

**Comment by dalton264** [comment]
I have around 4819 cards that show up none are suspended

**Comment by AnKingMed** [comment]
Can you export your entire collection without media and upload here?   And a screenshot of your addon settings

**Comment by dalton264** [comment]
I received a message saying I couldnt upload my collection here because it wasnt a supported file type 
I will put a link from google drive hopefully that will work 
https://drive.google.com/file/d/1y0fExVKd1hZwP4wIPx1TMq_6KuPQBlHq/view?usp=sharing

![image](https://user-images.githubusercontent.com/121759060/212447084-c69c9f86-7d27-4f8b-a543-b2a338280267.png)

**Comment by AnKingMed** [comment]
I did this search and it worked just fine for me:
`("deck:Gross anatomy both semester" -is:suspended) is:new`
