### ISSUE TITLE
 Exam notifier unsupported operand error

### ISSUE THREAD

**Issue by guillem-palau-salva** [AnKing-Memberships/ankiweb-placeholder#24]
## Which add-on is this about?
 Exam notifier

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Error upon loading Anki

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54 qt5
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.56 (07fd88dd) Python 3.9.15 Qt 5.15.2 PyQt 5.15.5
Platform: Windows-10-10.0.19044
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-17 23:42:03

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 43, in cmd
File "aqt.webview", line 150, in _onCmd
File "aqt.webview", line 614, in _onBridgeCmd
File "_aqt.hooks", line 4887, in __call__
File "C:\Users\peach\AppData\Roaming\Anki2\addons21\exam_notifier\deck_options.py", line 150, in on_webview_did_receive_js_message
DeckConf(self._main_window, deck_legacy)
File "aqt.deckconf", line 43, in __init__
File "aqt.deckconf", line 77, in setupConfs
File "aqt.deckconf", line 94, in loadConfs
File "aqt.deckconf", line 118, in onConfChange
File "aqt.deckconf", line 228, in loadConf
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

```

```

**Comment by AnKingMed** [comment]
Should be resolved with latest public release
