### ISSUE TITLE
Uworld QID

### ISSUE THREAD

**Issue by all259** [AnKing-Memberships/ankiweb-placeholder#27]
## Which add-on is this about?

UWorld QID TO search Anking

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?
V12

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.53
```

#### Your question

*A clear and concise question about the add-on.*

I don't see the uworld menu in the top of the screen. Is there an add on code that will let me access it?

**Comment by AnKingMed** [comment]
It only shows up in the browser view and it must be downloaded from the membership/patreon (NOT the ankiweb placeholder listing). Can you confirm that's the case?

**Comment by all259** [comment]
Yes, I do not see where the download is. Where is it?

**Comment by all259** [comment]
I don't see it on the page.

**Comment by DoctorToBeIn23** [comment]
> I don't see it on the page.

Are you talking about the ankiweb addon page or the AnKing membership add on page?

**Comment by all259** [comment]
I am talking about the Anking membership add on page.

**Comment by all259** [comment]
https://courses.ankipalace.com/products/anking-membership-bronze-tier/categories/4374320/posts/2157381293

this page

**Comment by DoctorToBeIn23** [comment]
https://courses.ankipalace.com/products/anking-membership-platinum-tier/categories/4385543/posts/2157381202

Jacob D. King
Class of 2023
Rocky Vista University
255 E. Center St.
Ivins, UT 84738
***@***.***
***@***.***

**Comment by all259** [comment]
It says I cannot access that link. Would you mind posting the add on here or something? I just want to get started.

**Comment by DoctorToBeIn23** [comment]
Are you an AnKing bronze member?

**Comment by all259** [comment]
Should we have access to that as a bronze member? I was under the impression that you would.

**Comment by all259** [comment]
![Screen Shot 2023-01-20 at 1 45 05 PM](https://user-images.githubusercontent.com/123184699/213780773-38618570-ab44-40d4-9b5c-8cf97f6456fa.png)

Based on the listed benefits!

**Comment by AnKingMed** [comment]
You should have access. If you login at www.ankingmed.com/memberships, you should see a section for addons further down and in there is a section for the uworld addon. In that section is a download link.

**Comment by all259** [comment]
Found it thanks!
