### ISSUE TITLE
Exporting QIDs 

### ISSUE THREAD

**Issue by robhornberger** [AnKing-Memberships/ankiweb-placeholder#28]
## Which add-on is this about?
Uworld 
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?
⁨2.1.56
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question
I am having trouble exporting the QIDs to make a custom uworld study session. Everytime I hit export it brings ups a dialouge explain about the different ways that I can keep track of what cards I've exported. However I never get the QIDs added to my clipboard. I've been using this search criteria deck:Anking tag:#AK_Step1_v12::#UWorld prop:ease<=2 
*A clear and concise question about the add-on.*

**Comment by papamorf** [comment]
I have AnkiHub with the 12th version, plus the latest version 2.1.56 and the add-on is not showing on my browser search.

**Comment by DoctorToBeIn23** [comment]
Are you on windows or Mac? I have not been able to reproduce this issue.

**Comment by papamorf** [comment]
I am using the latest version on Mac.

**Comment by DoctorToBeIn23** [comment]
can you export your collection and upload it to google drive and send it to me and I can see if the issue persists?

**Comment by AbdullahOmira** [comment]
Hello, I have the same problem on anki-2.1.56, ⁨2.1.61. both 1.16, 1.19 versions of the addon.
I can export collection and upload it if that would help.

**Comment by lwoods1** [comment]
I am also on 1.19 and Anki 2.1.58 having the same issues on Windows. Whenever I use any search term or the search term that @AbdullahOmira mentioned, it says that the addon can't find any UWorld questions when it is set to "auto". or when I click in the Browse section: UWorld--> Version--> Step 1 (change to step 1 from auto) it pulls up a box that says do you want these questions recorded on the clipboard so they won't get reused. But no QID's get put on any clipboard unfortunately

**Comment by lwoods1** [comment]
this i s what the addon config says: 

{
    "(if many notes are selected): qids by order of notes (true) or by random (false)": false,
    "Anking_Deck_version": 12,
    "Auto": true,
    "Browser menu used": "&UWorld",
    "MCAT": false,
    "Max elements in exported string": 40,
    "Only one uworld qid per anki note on same export if sufficient other qids": true,
    "Relevant tags": [
        "Step1"
    ],
    "store non matched qids": true
}

**Comment by DoctorToBeIn23** [comment]
this was just fixed and will be updated very soon.
