### ISSUE TITLE
UWorld QID Add-on

### ISSUE THREAD

**Issue by papamorf** [AnKing-Memberships/ankiweb-placeholder#29]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.56
```

#### Your question

*I have AnkiHub with the 12th version, plus the latest version 2.1.56 and the add-on is not showing on my browser search. Why this happened?*

**Comment by AnKingMed** [comment]
Did you download it from AnkiWeb or from the membership? (It needs to be the one from the membership and not the placeholder on AnkiWeb). Are you in the browser menu? It does not show up in the main screen

**Comment by papamorf** [comment]
I have it from the membership.

**Comment by DoctorToBeIn23** [comment]
@papamorf are you still having issues with this?

**Comment by papamorf** [comment]
No, I am not. I re-installed the add-on and it worked well. Thank you!
