### ISSUE TITLE
Placeholder - UWorld QID to Anki Search: Not working

### ISSUE THREAD

**Issue by pyunjihe** [AnKing-Memberships/ankiweb-placeholder#3]
## Which add-on is this about?
Placeholder - UWorld QID to Anki Search
https://ankiweb.net/shared/info/607963104

#### Problem description
*Please describe the issue concisely here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
Thanks for continuously developing the Anking deck for medical students! I just purchased the membership, however, I am having the same issue as others- the top bar “Uworld” does not show up for me even after restarting Anki several times.
I am running Anki ⁨version 2.1.49 (dc80804a)⁩ on windows, and the Anking version is v11.

Unfortunately, it does not. I thought the UWorld top bar would only show up in the browser window if I purchase the membership. However, I still do not see it, and that is why I was emailing you. It seems that many others are having the same issue as me in the comments here:
https://courses.ankipalace.com/products/anking-membership-bronze-tier/categories/4374320/posts/2157381293

#### Checklist
*Please replace the space inside the brackets with an **x** if the following items apply:*
 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [x ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Anki ⁨version 2.1.49 (dc80804a)⁩ on window```

#### Error message (if any)
*If you've received an error message, please copy and paste it between the backticks below:*
N/A

**Comment by AnKingMed** [comment]
Can you try with just this addon enabled and all others disabled?

**Comment by AnKingMed** [comment]
Ok I have a thought. Can you send me a list of all your addons? Screenshot is ok

**Comment by AnKingMed** [comment]
Awesome! Glad we figured it out!
