### ISSUE TITLE
Downloaded but no Uworld in top bar

### ISSUE THREAD

**Issue by ankween** [AnKing-Memberships/ankiweb-placeholder#30]
## Which add-on is this about?

Uworld QID

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I downloaded the google drive link and downloaded into anki. Restarted anki and there is no uworld at the top of the screen so I dont know how to use the add on

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.## Version ⁨2.1.54 (b6a7760c)⁩
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Are you in the browser screen?

**Comment by ankween** [comment]
Figured it out problem resolved!

**Comment by DoctorToBeIn23** [comment]
@ankween would you be so kind as to tell us what the issue was and how you solved it?
