### ISSUE TITLE
AnkingStudyTimer

### ISSUE THREAD

**Issue by LuisJ3011** [AnKing-Memberships/ankiweb-placeholder#31]
## Which add-on is this about?
StudyTimer

 - [ X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ X] I've checked if anyone else asked this question before by looking through the issue reports.

2.1.54

How can i change the time on the timer?

**Comment by AnKingMed** [comment]
Under the AnKing menu -> King of Study Timers -> Settings and then you can adjust any setting you want
