### ISSUE TITLE
Missing Sketchy Micro tag: "tag:#AK\_Step1\_v12::#SketchyMicro::01\_Bacteria::04\_Gram\_(-)\_Cocci"

### ISSUE THREAD

**Issue by aaront19** [AnKing-Memberships/ankiweb-placeholder#32]
#### Problem description

Within AKv12 the tag: "tag:#AK\_Step1\_v12::#SketchyMicro::01\_Bacteria::04\_Gram\_(-)\_Cocci" is missing. The subfolder "tag:#AK\_Step1\_v12::#SketchyMicro::01\_Bacteria" skips from "tag:#AK\_Step1\_v12::#SketchyMicro::01\_Bacteria::03\_Gram\_(+)\_Branching\_Filamentous\_Rods" to "tag:#AK\_Step1\_v12::#SketchyMicro::01\_Bacteria::05\_Gram\_(-)\_Bacilli\_-\_Enteric\_Tract"

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.56Qt6
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
N/A
```

**Comment by AnKingMed** [comment]
I'm on vacation and don't have my computer but check the "retired" lessons tag. Is it there?

**Comment by aaront19** [comment]
My apologies for disrupting your vacation. I just checked the retired lessons and the tag is not there either

**Comment by AnKingMed** [comment]
yeah some of those are
