### ISSUE TITLE
Uworld QID

### ISSUE THREAD

**Issue by amoghiyer17** [AnKing-Memberships/ankiweb-placeholder#33]
## Which add-on is this about?
Uworld QID to Search

#### Problem description

When I import in a list of questions from UWorld, I am no longer informed which cards are tagged and available in anki like I was before.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [ X] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ X] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by DoctorToBeIn23** [comment]
Make sure you have the most recent version. Delete and redownload the add on and it should fix the issue.
