### ISSUE TITLE
Calculate New Cards to Do add on throwing an error

### ISSUE THREAD

**Issue by younkert** [AnKing-Memberships/ankiweb-placeholder#36]
I am running Anki version ⁨2.1.56 on an M1 mac. Had no issue with older versions of Anki so I figure this is an update issue. I also tried downloading the latest .zip on the members website.

When loading '⁨Calculate New Cards To Do⁩':
⁨
_Traceback (most recent call last):
  File "aqt.addons", line 247, in loadAddons
  File "/Users/Teddy/Library/Application Support/Anki2/addons21/calculate_new/__init__.py", line 3, in <module>
    from . import menu
  File "/Users/Teddy/Library/Application Support/Anki2/addons21/calculate_new/menu.py", line 14, in <module>
    setup_menu()
  File "/Users/Teddy/Library/Application Support/Anki2/addons21/calculate_new/menu.py", line 8, in setup_menu
    menu = get_anking_menu()
  File "/Users/Teddy/Library/Application Support/Anki2/addons21/calculate_new/gui/anking_menu.py", line 72, in get_anking_menu
    menu = a.menu()
AttributeError: 'QAction' object has no attribute 'menu'_

**Comment by younkert** [comment]
problem resolved. looks like the version 1.2.zip file is also posted on that page (in addition to the updated version). Might want to consider deleting.

**Comment by younkert** [comment]
Also, might you consider adding an example of how to query for a subdeck? e.g. Anking Step 1 only I'm struggling to determine the syntax needed beyond 'deck:AnKing:Step 1'

**Comment by AnKingMed** [comment]
Where are you seeing the version 1.2 zip file?  Are you on Patreon or the Membership? I didn't realize that was there so I'll remove it

For the search, you might be wanting `'deck:AnKing:Step 1' is:new` or something like that

**Comment by younkert** [comment]
It was on the sidebar of the Membership page. 

As for the search, `'deck:AnKing:Step 1' is:new` and `'deck:AnKing:Step 1'` doesn't return any cards. 

The only search that works is `deck:AnKing`. I did try to change the name of `Step 1` deck to `Step_1` incase there was some issue with string search and spaces, but no luck. The Membership page used to list an example that allowed it to work, but when I updated I lost my input and the page didn't list the example. Maybe you have it archived?

**Comment by AnKingMed** [comment]
Would you mind sending a screenshot? I can't find that old link

Try making the search in the browser of Anki first because the add-on just uses the browser search.  My search looks like this: `"deck:AnKing Overhaul for Step 1 & 2::Step 1" is:new`

**Comment by younkert** [comment]
Do you mean a screenshot of the page as I see it?
![Screenshot 2023-02-15 at 8 11 06 PM](https://user-images.githubusercontent.com/24940843/219233446-01ad0165-0442-49b6-b1b0-13db9cf5f4ee.png)

Your suggestion worked. Looking at the config file directly the implicitly placed `\`s in `"\"deck:AnKing::Step 1\" is:new"` seem to the what makes the query return something. Might be worth posting an example in the description on the add on page.

**Comment by AnKingMed** [comment]
Thanks. I didn't realize that was still there but it's gone now. I'll add the description to my todo list! Thanks for the feedback!
