### ISSUE TITLE
PROBLEM WITH UWORLD QIDS IN WINDOWS .

### ISSUE THREAD

**Issue by NOITAC** [AnKing-Memberships/ankiweb-placeholder#39]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##54 (b6a7760c)⁩
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by NOITAC** [comment]
NO ERROR SHOWED.

**Comment by AnKingMed** [comment]
What problem are you having? Can you provide more details?

**Comment by NOITAC** [comment]
I AM CURRENTLY USING V 11 VERSION DECK IN MY WINDOWS ,Version ⁨2.1.54 (b6a7760c)⁩. 
AFTER ADDING U WORLS QID ADDON IT IS NOT WORKING AT ALL, AND WHEN I TRIED TO CHECK CONFIGURATIONS IT IS EMPTY NOT SHOWING ANYTHING.

**Comment by NOITAC** [comment]
![1111111111](https://user-images.githubusercontent.com/126222062/221340604-e6fa711e-6d56-465b-b0ba-d643fd62ff98.png)
![22222](https://user-images.githubusercontent.com/126222062/221340619-49bdade9-a65a-4233-9de0-7a609d63142f.png)
![33333333](https://user-images.githubusercontent.com/126222062/221340628-c32fc96c-2a0e-4f4d-b448-95a05c0ea849.png)

I TRIED TO ATTACH IMAGES , NOT SURE WHEATHER U CAN SEE IT OR NOT

**Comment by AnKingMed** [comment]
You have the placeholder. Delete that addon and download the addon from the membership dashboard https://www.ankipalace.com/memberships  (or patreon if you are on there)

**Comment by AnKingMed** [comment]
Also, note that the UWorld menu will only show up in the browser

**Comment by NOITAC** [comment]
IS IT THE PAID ADD ON ??

**Comment by NOITAC** [comment]
SO I HAVE TO OPEN ANKI WEB IN BROWSER ,LOGIN TO MY ACCOUNT AND SEARCH THERE
