### ISSUE TITLE
uworld QID not working 

### ISSUE THREAD

**Issue by ysmnbo** [AnKing-Memberships/ankiweb-placeholder#4]
## Which add-on is this about?
uworld QID new V12 tag update

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

hi! thanks for updating this add on, it's amazing. I updated the addon as well as the tags V12. But not it's not showing any of my step 1 QIDs (even tho it was normally beforehand) (and just to clarify the add on it is still configured step 1). Also when I configure the add-on to Step2, it's also not recognizing any of the QIDs. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.⁨2.1.49
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you send me some example QIDs to test?

**Comment by ysmnbo** [comment]
hi yes, so for step 1, this is from a block and most of them previously worked give or take a few: 8323, 18735, 1421, 1341, 21589, 910, 116, 1933, 907, 1442, 8702, 12029, 587, 866, 966, 1936, 1401, 1689, 8481, 1323, 15712, 11462, 11685, 20008, 493, 105534, 12023, 21404, 11609, 15765, 14899, 20275, 1150, 20, 19802, 15683, 11676, 15745, 11682, 501 

Now none of them do for me

**Comment by AnKingMed** [comment]
Most of them worked for me.  Can you send pics of your tags and your uworld addon config?

**Comment by ysmnbo** [comment]
<img width="701" alt="Screen Shot 2022-06-18 at 9 23 49 PM" src="https://user-images.githubusercontent.com/107778334/174462091-bcaa2440-0bc1-439b-9b2e-2b64fb9cd2df.png">
<img width="408" alt="Screen Shot 2022-06-18 at 9 24 47 PM" src="https://user-images.githubusercontent.com/107778334/174462107-270af78d-e819-42a4-b714-6c3f34310640.png">

Sorry, I'm not sure if you wanted a picture of something more specific for the tags

**Comment by AnKingMed** [comment]
Looks like you don't have the latest update of tags posted on Reddit and that's why it's not working.  You have the new addon, but not the tags

**Comment by AnKingMed** [comment]
Yeah that's it. Make sure you follow all the instructions to update
