### ISSUE TITLE
UWorld Add on not showing all related cards for QIDs 

### ISSUE THREAD

**Issue by nicepainting34** [AnKing-Memberships/ankiweb-placeholder#41]
## Which add-on is this about?
UWorld Add On

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

When I import UWorld QID from my UWorld Qbank, it doesn't show all related  QIDs. instead, I get this message:
"some entered QID didn't have matching notes in the collection and were ignored for the search" and it proceeds to show only a few questions that match with the total list i inputed. I have the COMLEX level 1 assessment bank that contains Step1 and COMLEX questions.

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
V12

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by DoctorToBeIn23** [comment]
Unfortunately, the question set you purchased as different QIDs than the normal just step 1 question set. They have the same questions but the QIDs are different. Unfortunately, your three options are:
1. Help tag the questions so the future students doing the same as you can benefit. 
2. Contact Uworld and ask if you can switch
3. If they dont let you switch and money is not at all a worry purchase the normal question set that doesn't add in the COMLEX questions.
