### ISSUE TITLE
UWORLD ANKI ADD ON DOES NOT IMPORT ANY CARD

### ISSUE THREAD

**Issue by sram87** [AnKing-Memberships/ankiweb-placeholder#42]
When I copied and paste the QID from UWorld to Anki I got this message "some entered qids didn't have matching notes in the collection and were ignored for the search". None of the questions apparently have notes available to import. 
![Image 3-3-23 at 10 46 AM](https://user-images.githubusercontent.com/126896474/222764237-1031ed4a-090f-4e5a-b966-50402664b8ba.jpg)
 
I have the Anki membership active. I tried everything. What can I do?

**Comment by DoctorToBeIn23** [comment]
1. Please send me a picture of your config.
2. What step exam are you studying for
3. Did you sign up for UWorld with the OMM DO practice questions package?

**Comment by sram87** [comment]
1. Config???
2.  Step 2
3. ??? , I have the one year UWorld package for step 2.

**Comment by DoctorToBeIn23** [comment]
1. Go to your add ons click on the UWORLD QID add on and click config
2. Did you select in the add on your studying for step 2?
3. Double checking are you a DO and did you pay for the additional COMLEX questions?

**Comment by sram87** [comment]
2. Correct
3. I am an MD Student, not DO. I paid the bronze membership on Anki. At UWorld I have the 1 year membership.

**Comment by DoctorToBeIn23** [comment]
You need to delete the add on and redownload it from the bronze membership page again, this will solve the issue. After downloading make sure in the bar under Uworld you select the proper step exam your studying for.

**Comment by sram87** [comment]
Does not work. I delete it and redownload it from the bronze membership.  This one. I got the same error message.
![Image 3-3-23 at 11 25 AM](https://user-images.githubusercontent.com/126896474/222773862-8c2102f9-7350-42d5-8fa8-267d7d6850e8.jpg)

**Comment by sram87** [comment]
![Image 3-3-23 at 11 27 AM](https://user-images.githubusercontent.com/126896474/222774037-f0aad434-16a5-436d-a5ff-26400f578b38.jpg)

**Comment by DoctorToBeIn23** [comment]
Can you show me the name of your add on like you did before?

**Comment by sram87** [comment]
![Image 3-3-23 at 11 34 AM](https://user-images.githubusercontent.com/126896474/222775923-7214eb2e-ccd1-4dc8-aece-3ffd8ee9a616.jpg)
![Image 3-3-23 at 11 35 AM](https://user-images.githubusercontent.com/126896474/222775947-32df103d-7652-40a8-bfb7-e18dad1f459f.jpg)


Add on and Config

**Comment by DoctorToBeIn23** [comment]
You have it set to step 1 according to the config. Switch the "step1" to "step2" and then if you have an issues send a screen shot of the actual issue your now running into.

**Comment by sram87** [comment]
<img width="638" alt="Screen Shot 2023-03-03 at 11 42 07 AM" src="https://user-images.githubusercontent.com/126896474/222777627-f24534c9-f303-45f4-b049-603c58674459.png">

Switch to Step 2, I closed and opened the app. Same issue
![Image 3-3-23 at 11 44 AM](https://user-images.githubusercontent.com/126896474/222777979-82a93335-1b36-4f3b-af4a-5aa99bc7a480.jpg)

**Comment by DoctorToBeIn23** [comment]
Can you show me a picture of your tags?

**Comment by sram87** [comment]
![Image 3-3-23 at 11 47 AM](https://user-images.githubusercontent.com/126896474/222778640-eda8ef3f-a4d9-437f-b695-47a511e490f7.jpg)

**Comment by sram87** [comment]
The Anki hub is requesting me to sign up, the email is not recognized. I did the registration, its requesting me to pay again another subscription. There's no other way you can connect remote to verify?

**Comment by sram87** [comment]
I did the download from ankipalace

**Comment by DoctorToBeIn23** [comment]
> which deck?

The AnKing deck :)

**Comment by sram87** [comment]
Does not work! thanks anyway! Paid subscription for nothing! I'm going to cancel thanks!

**Comment by DoctorToBeIn23** [comment]
This is confirmed and is working, you must be missing a step. I ran the first 4 questions that you tried to and this is the result I got. I can tell you were not updated on AnkiHub to AnKing v12.

![image](https://user-images.githubusercontent.com/60248099/222804435-9fee2b60-a60a-44bf-8a0a-68d7dafc720c.jpeg)

**Comment by AnKingMed** [comment]
@sram87 you can download v11 of the deck on reddit [here](https://www.reddit.com/r/medicalschoolanki/comments/swjqzh/anking_overhaul_step_1step_2_version_11_update/)

V11 does not have all the UWorld tags but it does have a decent amount, mostly for Step 1

V12 of the deck is significantly improved and is on AnkiHub. You have to have an AnkiHub subscription in order to use this version of the deck.  [This post](https://www.reddit.com/r/medicalschoolanki/comments/wedic1/anking_version_12_to_automatic_syncing_forever_on/) explains how to download it, but the most useful things are the [AnKing Deck wiki](https://tinyurl.com/ankingdeck) and the [AnkiHub tutorial video](https://youtu.be/_pZFj-1e0nE) (I **highly** recommend you watch this first)

If you get stuck trying to update to those, we can try to help. The UWorld QID add-on will not work unless you're on v11 or v12 of the deck. If you're on an older version, we would strongly recommend you update anyway because the new ones are quite a bit better
