### ISSUE TITLE
Importing UWorld QIDs leads to indefinite "processing..." error

### ISSUE THREAD

**Issue by MightyBooman** [AnKing-Memberships/ankiweb-placeholder#43]
## Which add-on is this about?
UWorld QID

#### Problem description

The add-on works normally, but after several consecutive imports (i.e. searching one at a time after completing a block), the normal "processing..." pop-up appears indefinitely. I have to force quit Anki and reboot.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.56 qt 6
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
Edit:
No error message; only an indefinite normal pop-up.

![uworld qid processing](https://user-images.githubusercontent.com/98279951/223871733-5c7ff08f-826f-4b78-995f-53477756fdc8.jpg)

```

**Comment by AnKingMed** [comment]
Are you on the latest version? (I think it's 19)

**Comment by MightyBooman** [comment]
I should be, but I'm not sure how to confirm. I recently updated on 3/4 when I received the email

**Comment by damronatron** [comment]
I have not had this issue. @MightyBooman do you have the addon set to "auto" or to a specific qbank (ie, step 1,2,3). I have found it takes longer on auto.

**Comment by MightyBooman** [comment]
@damronatron I have it set to step 1. I have been having this issue since before the most recent update FWIW

**Comment by MightyBooman** [comment]
I'm beginning to think it's on my end, but not sure of the root cause. I just tried downloading a couple of different decks to a separate profile and had the same "Processing..." pop-up appear indefinitely

**Comment by DoctorToBeIn23** [comment]
> I'm beginning to think it's on my end, but not sure of the root cause. I just tried downloading a couple of different decks to a separate profile and had the same "Processing..." pop-up appear indefinitely

Have you been able to resolve this?

**Comment by MightyBooman** [comment]
@DoctorToBeIn23 I appreciate the followup. I honestly don't even know where to start with troubleshooting. I'm choosing to learn to live with it since it seems like it's a unique issue and it's not terribly disruptive at this time

**Comment by DoctorToBeIn23** [comment]
Well you are a trooper and if you end up figuring it out please let us know.

**Comment by AnKingMed** [comment]
That's good to hear. I'll close this for now but if things recur let us know
