### ISSUE TITLE
Uworld QID No Longer Showing Popup with Ids whether a Q has a matching ID or not

### ISSUE THREAD

**Issue by ballin4dapandas** [AnKing-Memberships/ankiweb-placeholder#47]
## Which add-on is this about?

UWorld QID converter

#### Problem description

When using the convert QID to tag search, the popup that used to say whether QIDS matched tags or not is no longer showing up. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x - not all but most] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.57
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

NA

https://user-images.githubusercontent.com/46008277/229621642-fad5b335-c333-4298-b3c6-fb8778504260.mp4

**Comment by ballin4dapandas** [comment]
as an update i disabled all the addons except for uworldqid and it still doesn't show the popup

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 can you follow up on this?

**Comment by ballin4dapandas** [comment]
I got it from the patreon page; I believe it is version addon version 1.19. I just checked the anking mastery page and I tried my ankihub login but that didn't work so I assume it is a different login altogether with a separate subscription from patreon. 

The addon works as intended except for the popup stating which QIDs matched / didn't match with tags as depicted in the video. I've tried this on different windows PCs with the same result on different anki versions all above 2.5

**Comment by ballin4dapandas** [comment]
Wanted to bump this. don't mean to be pushy but not knowing which questions don't have matching cards is understandably stressful and i'm just not taking the time to go through each question and see if there is a card that matches. i'm hoping this bug gets fixed so i can go back and create cards for whatever questions don't have matching QIDs once this feature works again

**Comment by AnKingMed** [comment]
You're referring to this right?
![image](https://user-images.githubusercontent.com/57678116/232250082-4f209f00-a9e4-496f-8e74-f3cd49dcc084.png)

**Comment by DoctorToBeIn23** [comment]
Sorry also for the late reply, I made a new email a few months ago so I need to update my notifications. Please send us screenshots with as much detail as possible including what your config looks like as well as which QIDs your using.

**Comment by ballin4dapandas** [comment]
I understand, we are all busy and we I posted a video earlier in the thread that showed the issue with the QIDs I used. For completion's sake the QIDs in the video were "4454, 19934, 4676" & "12501, 4469, 4738, 19174, 21157, 4452"

I just tried it with this string of QIDs too and same issue - the pop-up just doesn't show up

. "17156, 16042, 4150, 15709, 3976, 2341, 7010, 2759, 3231, 4154, 19227, 4612, 3336, 3878, 4134"

**Comment by ballin4dapandas** [comment]
> You're referring to this right? ![image](https://user-images.githubusercontent.com/57678116/232250082-4f209f00-a9e4-496f-8e74-f3cd49dcc084.png)

yes i am. My laptop has 2.1.55 and my desktop has a later version but the pop up doesn't show up on either pc.

**Comment by AnKingMed** [comment]
Try `4454, 19934, 4676`

Then try `4454, 19934, 4676, 111111`

Does the second one have a pop up?

**Comment by ballin4dapandas** [comment]
yes it did
![image](https://user-images.githubusercontent.com/46008277/232254053-c291f41b-3061-4333-a2be-f0c72b55dfce.png)

**Comment by AnKingMed** [comment]
So your pop up works. The reason you're not getting a popup is because it's finding them for every QID
