### ISSUE TITLE
Issue with Uworld beta add on

### ISSUE THREAD

**Issue by RickenRT** [AnKing-Memberships/ankiweb-placeholder#48]
I am a member, have the latest versions, downloaded the uworld search add on and it will not show up on my upper bar to select the things i need to use the add on

**Comment by RickenRT** [comment]
Im not sure what you mean by that. Could you explain?

[OSU Logo]<https://go.okstate.edu/>
RILEIGH RICKEN she/her
OMS II, Ensign US Navy
OSU-CHS College of Osteopathic Medicine
775.301.7752 • 1111 W 17th Street Tulsa, OK • https://linqapp.com/rileigh_ricken?r=link<https://https/linqapp.com/rileigh_ricken?r=link>
[signature_2635679254]LGBTQ Safezone Ally


From: AnKingMed ***@***.***>
Date: Monday, April 17, 2023 at 10:09 AM
To: AnKing-Memberships/ankiweb-placeholder ***@***.***>
Cc: Ricken, Rileigh ***@***.***>, Author ***@***.***>
Subject: Re: [AnKing-Memberships/ankiweb-placeholder] Issue with Uworld beta add on (Issue #48)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe

Are you in the Browser window?

**Comment by AnKingMed** [comment]
In the main Anki screen, click "Browse" at the top.

Can you send a screenshot of where you're looking if you can't find it after doing that?

**Comment by RickenRT** [comment]
UWorld doesn’t come up on my top bar like my Amboss does. Ive checked all my versions updates etc but I cant get it to work

[Graphical user interface, text, application  Description automatically generated]
[OSU Logo]<https://go.okstate.edu/>
RILEIGH RICKEN she/her
OMS II, Ensign US Navy
OSU-CHS College of Osteopathic Medicine
775.301.7752 • 1111 W 17th Street Tulsa, OK • https://linqapp.com/rileigh_ricken?r=link<https://https/linqapp.com/rileigh_ricken?r=link>
[signature_3499313957]LGBTQ Safezone Ally


From: AnKingMed ***@***.***>
Date: Monday, April 17, 2023 at 10:20 AM
To: AnKing-Memberships/ankiweb-placeholder ***@***.***>
Cc: Ricken, Rileigh ***@***.***>, Author ***@***.***>
Subject: Re: [AnKing-Memberships/ankiweb-placeholder] Issue with Uworld beta add on (Issue #48)
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe

In the main Anki screen, click "Browse" at the top.

Can you send a screenshot of where you're looking if you can't find it after doing that?

**Comment by AnKingMed** [comment]
If you can see an AMBOSS thing, you're in the wrong place.  You need to be in the browser view

![CleanShot 2023-04-17 at 11 23 37@2x](https://user-images.githubusercontent.com/57678116/232534173-469d3dc5-9d1b-4af0-81f9-857fed7d28a6.jpg)

If you can't find it, please send a screenshot or pic of what you're looking at so we can see what's going on
