### ISSUE TITLE
Placeholder Add-on not showing up at all 

### ISSUE THREAD

**Issue by gyee01** [AnKing-Memberships/ankiweb-placeholder#49]
## Which add-on is this about?
Placeholder 

#### Problem description

*I input the Add-on code into my Anki macOS app. Restarted my Anki. I do not see a "UWorld" tab on the top left. I re-added the Add-on afterward and still nothing*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.61
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by gyee01** [comment]
Hi,

This is for the placeholder add-on. I’d like to use it to migrate the question IDs over to Anki so I can review based on wrong questions.

Greg

**Comment by AnKingMed** [comment]
We have a lot of placeholder addons. They're just placeholders for beta addons that are being tested on our memberships. 

https://courses.ankipalace.com/anking-membership-add-ons

**Comment by gyee01** [comment]
Hi,

Oh, I didn't know that. Sorry for the confusion!

https://ankiweb.net/shared/info/607963104

This one I believe. In the little gif, it shows that there's supposed to be
a UWorld tab on the top left after downloading the add-on.

[image: image.png] and this is what I see.

**Comment by AnKingMed** [comment]
Yeah that is just a placeholder.  The actual addon is available after purchasing a membership

**Comment by gyee01** [comment]
Hi,

Ok that sounds great. I do have a membership to AnkiHub and Anki Palace.
Where would I find the actual add-on?

**Comment by gyee01** [comment]
Hi

Nevermind, I got it! Thanks!
