### ISSUE TITLE
QID fails to detect UWSA1/UWSA2 sub-tags on Step2_v12

### ISSUE THREAD

**Issue by cafelinked** [AnKing-Memberships/ankiweb-placeholder#5]
## Which add-on is this about?
**uworld_qid_to_anki_search**

#### Problem description
Unable to pull question list from UWSA1 for Step 2CK. Isolated issue. Unknown for regular Qbank (have not started it yet).

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Sample QID from UWSA1 (Step 2): 6840, 6850, 6851, 6855
Unable to pull any question that are tagged under UWSA1 & UWSA2 for Step 2. Likely due to placed QIDs placed under UWSA1/UWSA2 Tags, rather than directly under parent UWorld tag.

Sampled a regular qbank QID: 10441, 10553, 10068
Pulls up the cards based on the QIDs typed. Regular does not seem to be an issue. 

Video if unable to see the attached file: https://dl.dropboxusercontent.com/s/gfnrrpmmqngyydi/6121f6ed-9f79-4990-8cba-80c431702709.mp4

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨2.1.50 (26d40c3a)⁩
Python 3.9.7 Qt 6.2.2 PyQt 6.2.2
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```
Video of bug being highlighted:
https://user-images.githubusercontent.com/106856406/177060150-50ea6c2e-70b1-46db-85cf-2a0bad893ea3.mp4

Config file:
![886c734d-ad32-4e3b-88fd-f71f4faffc51](https://user-images.githubusercontent.com/106856406/177060210-cb113b0b-b378-46e5-a8a3-d53bb1a916fe.png)

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 can you look into this? Looks like it might be that we need to move the UWSA tags around

**Comment by DoctorToBeIn23** [comment]
Thing is when you do one of the self assessments you can't even export all the numbers at the same time anyways. The add-on wasn't really built for the self assessments. I recommend people individually search the QIDs for each question on the self-assessment using the add-on https://ankiweb.net/shared/info/1052724801 Bettersearch.

**Comment by ANKIFETISH** [comment]
I have Bettersearch and I am able to search the cards corresponding to the QID. It is strange that in UWSA, QIDs are un-exportable. At this time, it not an issue for me hence I am okay with Bettersearch at this time. However, just a heads up for other users that may come across this similar issue, thought I might let you guys be aware of it at least. 

Having the QIDs under both works, though I am not too sure if this will further slow down the Browser. Not too sure if the slowness is my computer only, but whenever I have it qid add-on enabled, the scrolling is noticeably slow compared to when it is disabled. See video for example: https://dl.dropboxusercontent.com/s/shmvuik8063ajty/ee44ee97-7cc4-498d-86cb-1406ebb0abf7.mp4 

I can open this as a separate issue, if need be.

**Comment by DoctorToBeIn23** [comment]
Good to know, I do not have any issues with scrolling though. Haven't been able to replicate it either.

**Comment by ANKIFETISH** [comment]
Just tested few add-ons by disabling them: 

[Colorful Tags ](https://ankiweb.net/shared/info/594329229) add-on is conflicting with QID add-on. I have never used this add-on, so I have uninstalled it and it is much smoother.
