### ISSUE TITLE
Trying to install Uworld to anki search

### ISSUE THREAD

**Issue by weehoooo** [AnKing-Memberships/ankiweb-placeholder#54]
## Which add-on is this about?
Uworld to anki search

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I tried downloading the beta version of this. My anki said it was successfully installed so I restarted the application. After several time I was unable to see the Uworld bar at the top of my screen. Ive disabled the other add ons as well and restarted but was unsuccessful. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [X ] My issue disappears when I hold shift while starting Anki.
 - [ X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.62
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Are you in the browser?  Did you install this on ankiweb (the placeholder) or on the membership dashboard (as a file)?

**Comment by weehoooo** [comment]
I installed it on the membership dashboard to the anki application on the computer

**Comment by AnKingMed** [comment]
Are you in the browser?

**Comment by weehoooo** [comment]
ohh i see, it is showing up when I am in the browser. Thank you.
