### ISSUE TITLE
Bionic reading add-on won't disable

### ISSUE THREAD

**Issue by albc28** [AnKing-Memberships/ankiweb-placeholder#57]
## Which add-on is this about?
649714433 - Placeholder - BR

#### Problem description

Downloaded a group of add-ons to improve my anki, one of the add-ons in the group was the bionic reading which I dislike. I first tried disabling it, restarted anki and it didn't go away. Then i deleted it, but still didn't go away. I downloaded it again, and disabled it but it still affecting all my decks. When I restart anki holding shift key, it won't disable either. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
You need to install the add-on again and turn it off from the addon config

**Comment by albc28** [comment]
I deleted it again, copied the code and installed it, but when I click on the add-on it says it has no configuration. 

<img width="563" alt="image" src="https://github.com/AnKing-Memberships/ankiweb-placeholder/assets/135064360/ca8fd6c6-b527-4fd8-bc43-e0985bfebc3c">

**Comment by AnKingMed** [comment]
Looks like you downloaded the placeholder. Delete it and download the actual addon off the memberships site
