### ISSUE TITLE
Failed to reverse changes upon disabling the add-on

### ISSUE THREAD

**Issue by MightyBooman** [AnKing-Memberships/ankiweb-placeholder#8]
I gave bionic reading a try for a day, but ultimately decided that I'd prefer not to use it long term. After disabling the addon, only the Anking Overall note type reversed to normal. How do I revert the changes on the other note types?

**Comment by AnKingMed** [comment]
You  need to re-enable the add-on, go into the config and uncheck the note types. It adds a script to the note types so that's why it hasn't stopped. I'll update the instructions on patreon. Thanks for letting me know!
